# Generated by Django 6.0.3 on 2026-05-25 12:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("intelligence", "0001_initial"),
        ("screening", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="alert",
            name="user",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="alerts", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="client",
            name="created_by",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="clients_created", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="pdfreport",
            name="created_by",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="screeningmatch",
            name="watchlist_entry",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="screening_matches", to="intelligence.watchlistentry"),
        ),
        migrations.AddField(
            model_name="screeningrequest",
            name="approved_by",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="screenings_approved", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="screeningrequest",
            name="client",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="screenings", to="screening.client"),
        ),
        migrations.AddField(
            model_name="screeningrequest",
            name="created_by",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="screenings_created", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="screeningmatch",
            name="screening",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="matches", to="screening.screeningrequest"),
        ),
        migrations.AddField(
            model_name="pdfreport",
            name="screening",
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="report", to="screening.screeningrequest"),
        ),
        migrations.AddField(
            model_name="alert",
            name="screening",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="alerts", to="screening.screeningrequest"),
        ),
    ]
