# Generated by Django 6.0.3 on 2026-05-25 12:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RiskRule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=120)),
                (
                    "condition_type",
                    models.CharField(
                        choices=[
                            ("SOURCE_MATCH", "Source match"),
                            ("COUNTRY_MATCH", "Country match"),
                            ("SCORE_THRESHOLD", "Score threshold"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "source_code",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("OFAC", "OFAC"),
                            ("UN", "United Nations"),
                            ("EU", "European Union"),
                            ("FATF", "FATF/GAFI"),
                            ("INTERPOL", "INTERPOL"),
                        ],
                        max_length=20,
                    ),
                ),
                ("target_value", models.CharField(blank=True, max_length=120)),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        max_length=20,
                    ),
                ),
                ("weight", models.PositiveIntegerField(default=100)),
                ("enabled", models.BooleanField(default=True)),
                ("config", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ["-weight", "name"]},
        ),
        migrations.CreateModel(
            name="SanctionsSource",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("OFAC", "OFAC"),
                            ("UN", "United Nations"),
                            ("EU", "European Union"),
                            ("FATF", "FATF/GAFI"),
                            ("INTERPOL", "INTERPOL"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("SANCTIONS", "Sanctions"),
                            ("COUNTRY_RISK", "Country risk"),
                            ("LAW_ENFORCEMENT", "Law enforcement"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "source_format",
                    models.CharField(
                        choices=[("XML", "XML"), ("JSON", "JSON"), ("CSV", "CSV"), ("HTML", "HTML")],
                        max_length=16,
                    ),
                ),
                ("endpoint", models.URLField(blank=True)),
                ("landing_url", models.URLField(blank=True)),
                ("enabled", models.BooleanField(default=True)),
                ("sync_frequency", models.CharField(default="daily", max_length=40)),
                (
                    "health_status",
                    models.CharField(
                        choices=[("OK", "OK"), ("WARNING", "Warning"), ("ERROR", "Error")],
                        default="OK",
                        max_length=16,
                    ),
                ),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ["code"]},
        ),
        migrations.CreateModel(
            name="SyncJobLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "trigger",
                    models.CharField(choices=[("MANUAL", "Manual"), ("SCHEDULED", "Scheduled")], default="MANUAL", max_length=20),
                ),
                (
                    "status",
                    models.CharField(choices=[("RUNNING", "Running"), ("SUCCESS", "Success"), ("FAILED", "Failed")], default="RUNNING", max_length=20),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("items_processed", models.PositiveIntegerField(default=0)),
                ("items_created", models.PositiveIntegerField(default=0)),
                ("items_updated", models.PositiveIntegerField(default=0)),
                ("items_deactivated", models.PositiveIntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "source",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="sync_logs", to="intelligence.sanctionssource"),
                ),
            ],
            options={"ordering": ["-started_at"]},
        ),
        migrations.CreateModel(
            name="CountryRiskEntry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("country_name", models.CharField(max_length=120)),
                ("iso_code", models.CharField(blank=True, max_length=5)),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="LOW",
                        max_length=20,
                    ),
                ),
                ("list_name", models.CharField(blank=True, max_length=120)),
                ("notes", models.TextField(blank=True)),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("effective_date", models.DateField(default=django.utils.timezone.now)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("source", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="countries_risk", to="intelligence.sanctionssource")),
            ],
            options={"ordering": ["country_name"], "unique_together": {("source", "country_name", "list_name")}},
        ),
        migrations.CreateModel(
            name="WatchlistEntry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("external_id", models.CharField(blank=True, max_length=120)),
                (
                    "entry_type",
                    models.CharField(
                        choices=[("PERSON", "Person"), ("ENTITY", "Entity"), ("VESSEL", "Vessel"), ("COUNTRY", "Country")],
                        default="PERSON",
                        max_length=20,
                    ),
                ),
                ("primary_name", models.CharField(max_length=255)),
                ("normalized_name", models.CharField(db_index=True, max_length=255)),
                ("aliases", models.JSONField(blank=True, default=list)),
                ("countries", models.JSONField(blank=True, default=list)),
                ("nationality", models.CharField(blank=True, max_length=120)),
                ("date_of_birth", models.CharField(blank=True, max_length=120)),
                ("identifiers", models.JSONField(blank=True, default=dict)),
                ("remarks", models.TextField(blank=True)),
                ("source_url", models.URLField(blank=True)),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
                ("record_hash", models.CharField(db_index=True, max_length=40)),
                ("is_active", models.BooleanField(default=True)),
                ("listed_on", models.DateField(blank=True, null=True)),
                ("removed_on", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("source", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="entries", to="intelligence.sanctionssource")),
            ],
            options={"ordering": ["primary_name"], "unique_together": {("source", "record_hash")}},
        ),
    ]
