# Generated by Django on 2026-05-26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("intelligence", "0002_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sanctionssource",
            name="code",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
